version: 0.2
phases: 
    install:
       runtime-version: 
          dotnet: 5.0
    pre_build:
       commands:
          - echo Restore started on `date`
          - dotnet restore signalrprojectacs.csproj
    build:
       commands:
          - echo Build started on `date`
          - dotnet publish -c release -o ./build_output signalrprojectacs.csproj
artifacts:
    files:
       - build_output/**/*
       - deploy-scripts/**/*
       - appspec.yml 